<?php
/**
 * 角色绑定用户
 * User: kl
 * DateTime: 2021/11/17 1:06 上午
 */
namespace klphp\rbac\models;

use yii\base\Model;

class Assign extends Model{

    public $id;

    public $role;

    public function rules(){
        return [
            ['id','integer'],
            ['role','integer']
        ];
    }

    public function attributeLabels()
    {
        return [
            'id'=>'用户',
            'role'=>'用户组'
        ]; // TODO: Change the autogenerated stub
    }

}